"""add user relationship to books

Revision ID: 81528bcb3c21
Revises: 974f3b4ea868
Create Date: 2026-07-12 14:30:14.054470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81528bcb3c21'
down_revision = '974f3b4ea868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
